name = "plex_discord_rpc"
version = "1.0.0"
gleam = ">= 1.1.0"
target = "erlang"

description = "Plex to Discord RPC application created with Gleam"
licences = ["MIT"]
repository = { type = "github", user = "harrisonhoward", repo = "plex_discord_rpc" }

[dependencies]
gleam_stdlib = "~> 0.36"
survey = "~> 0.3"
shellout = "~> 1.6"
glint = "~> 0.18"
argv = "~> 1.0"
simplifile = ">= 1.7.0 and < 2.0.0"
dot_env = ">= 0.5.1 and < 1.0.0"
plex_pin_auth = ">= 1.0.1 and < 2.0.0"
repeatedly = ">= 2.1.1 and < 3.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
